/**
 * The French dictionary.
 *
 * Moved out of App.jsx so that the redesigned pages translate from the same
 * source as the original ones. Two dictionaries would drift: a phrase would be
 * French on the dashboard and English on Explore, and nobody would know which
 * file to correct.
 *
 * Keys are the exact English string as it appears on screen. The walker in
 * i18n.js looks each text node up here, so a new phrase added to a page needs
 * an entry here to be translated — an untranslated phrase falls back to
 * English rather than breaking.
 */

const FR_BASE = {
  Home: 'Accueil',
  Login: 'Connexion',
  Register: 'Inscription',
  Dashboard: 'Tableau de bord',
  Logout: 'Deconnexion',
  Currency: 'Devise',
  Language: 'Langue',
  English: 'Anglais',
  Francais: 'Francais',
  'Travel meets community': 'Le voyage rencontre la communaute',
  'Plan trips, sell event tickets, and connect with travelers.': 'Planifiez des voyages, vendez des billets et connectez-vous avec des voyageurs.',
  'GlobeTrotter brings itineraries, payments, groups, and media sharing into one polished React experience.': 'GlobeTrotter reunit itineraires, paiements, groupes et partage de medias dans une experience React soignee.',
  'Get Started': 'Commencer',
  'Sign In': 'Se connecter',
  'Shared travel plans': 'Plans de voyage partages',
  'Build itineraries together, invite friends, and track every booking.': 'Creez des itineraires ensemble, invitez des amis et suivez chaque reservation.',
  'Ticket monetization': 'Monetisation des billets',
  'Sell event tickets with receipts, commission tracking, and secure payment records.': 'Vendez des billets avec recus, suivi des commissions et paiements securises.',
  'Community feed': 'Fil communautaire',
  'Post photos, comment, like, and reach travel groups with media sharing.': 'Publiez des photos, commentez, aimez et rejoignez des groupes de voyage.',
  'Sign in': 'Connexion',
  'Create account': 'Creer un compte',
  Username: "Nom d'utilisateur",
  Password: 'Mot de passe',
  Interests: 'Centres d interet',
  'Already have an account?': 'Vous avez deja un compte ?',
  'New here?': 'Nouveau ici ?',
  'Create an account': 'Creer un compte',
  'Welcome back': 'Bon retour',
  'Access your itineraries, event receipts, and community groups in one place.': 'Accedez a vos itineraires, recus et groupes communautaires au meme endroit.',
  'Create itinerary': 'Creer un itineraire',
  'Join a group': 'Rejoindre un groupe',
  'Quick links': 'Liens rapides',
  Menu: 'Menu',
  Overview: 'Vue d ensemble',
  Itineraries: 'Itineraires',
  Discovery: 'Decouverte',
  Community: 'Communaute',
  Media: 'Medias',
  Resources: 'Ressources',
  Settings: 'Parametres',
  'My itineraries': 'Mes itineraires',
  'Destination recommendations': 'Recommandations de destinations',
  'Profile preferences': 'Preferences du profil',
  Notifications: 'Notifications',
  'No notifications yet.': 'Aucune notification pour le moment.',
  'Place autocomplete': 'Autocompletion de lieux',
  'Search catalogue': 'Rechercher dans le catalogue',
  Suggest: 'Suggerer',
  'Save preferences': 'Enregistrer les preferences',
  'Recent itineraries': 'Itineraires recents',
  'No itineraries found yet.': 'Aucun itineraire trouve.',
  'Recommended destinations': 'Destinations recommandees',
  Budget: 'Budget',
  Location: 'Lieu',
  Filter: 'Filtrer',
  Loading: 'Chargement',
  'Loading...': 'Chargement...',
  'No recommendations available yet.': 'Aucune recommandation disponible.',
  Title: 'Titre',
  'Hotel name': 'Nom de l hotel',
  'Hotel cost': 'Cout de l hotel',
  'Activity name': 'Nom de l activite',
  'Activity cost': 'Cout de l activite',
  'Place to visit': 'Lieu a visiter',
  'Place cost': 'Cout du lieu',
  'Start date': 'Date de debut',
  'End date': 'Date de fin',
  'Generate itinerary draft': 'Generer un brouillon d itineraire',
  Days: 'Jours',
  'Generate draft': 'Generer le brouillon',
  'Save draft': 'Enregistrer le brouillon',
  'Destination search': 'Recherche de destination',
  Search: 'Rechercher',
  Tag: 'Etiquette',
  Region: 'Region',
  Division: 'Departement',
  Subdivision: 'Arrondissement',
  City: 'Ville',
  Quarter: 'Quartier',
  'All regions': 'Toutes les regions',
  'All divisions': 'Tous les departements',
  'All subdivisions': 'Tous les arrondissements',
  'All cities': 'Toutes les villes',
  'All quarters': 'Tous les quartiers',
  'Max daily cost': 'Cout journalier maximal',
  Results: 'Resultats',
  Groups: 'Groupes',
  'Group name': 'Nom du groupe',
  Description: 'Description',
  'Create group': 'Creer un groupe',
  Join: 'Rejoindre',
  View: 'Voir',
  'No groups available yet.': 'Aucun groupe disponible.',
  'Trip suggestions': 'Suggestions de voyage',
  'Find matches': 'Trouver des correspondances',
  hotels: 'hotels',
  activities: 'activites',
  places: 'lieux',
  'No matches yet.': 'Aucune correspondance.',
  'Shared media feed': 'Fil de medias partages',
  'No media posts yet.': 'Aucune publication media.',
  Like: 'Aimer',
  Comment: 'Commenter',
  Share: 'Partager',
  'Resource management': 'Gestion des ressources',
  Type: 'Type',
  Hotel: 'Hotel',
  Activity: 'Activite',
  Place: 'Lieu',
  Name: 'Nom',
  Cost: 'Cout',
  'Add resource': 'Ajouter une ressource',
  'No entries.': 'Aucune entree.',
  Remove: 'Supprimer',
  'Review type': 'Type d avis',
  'Resource ID': 'ID de la ressource',
  Rating: 'Note',
  'Add review': 'Ajouter un avis',
  'Admin users': 'Utilisateurs admin',
  'Please log in to view your dashboard.': 'Veuillez vous connecter pour voir votre tableau de bord.',
  'Back to dashboard': 'Retour au tableau de bord',
  Owner: 'Proprietaire',
  Participants: 'Participants',
  'Shared with': 'Partage avec',
  Nobody: 'Personne',
  'Nobody yet': 'Personne pour le moment',
  'Total budget': 'Budget total',
  Duration: 'Duree',
  Progress: 'Progression',
  'not started': 'non demarre',
  Activities: 'Activites',
  'Places to visit': 'Lieux a visiter',
  'Event tickets': 'Billets evenementiels',
  'Payment receipt': 'Recu de paiement',
  Amount: 'Montant',
  Commission: 'Commission',
  Net: 'Net',
  'No payments recorded yet.': 'Aucun paiement enregistre.',
  'Trip stages': 'Etapes du voyage',
  'No stages calculated yet.': 'Aucune etape calculee.',
  'Open map': 'Ouvrir la carte',
  'Open in Google Maps': 'Ouvrir dans Google Maps',
  Directions: 'Itineraire',
  'Checklist item': 'Element de checklist',
  Add: 'Ajouter',
  'Update progress': 'Mettre a jour la progression',
  Status: 'Statut',
  'Not started': 'Non demarre',
  'In progress': 'En cours',
  Completed: 'Termine',
  Delayed: 'Retarde',
  'Current stage': 'Etape actuelle',
  Auto: 'Auto',
  'Completed stage IDs': 'IDs des etapes terminees',
  'Current location': 'Position actuelle',
  Percent: 'Pourcentage',
  'Share itinerary': 'Partager l itineraire',
  Permission: 'Permission',
  'View only': 'Lecture seule',
  'Can edit': 'Peut modifier',
  'Join itinerary': 'Rejoindre l itineraire',
  'Optional payment': 'Paiement optionnel',
  'Join trip': 'Rejoindre le voyage',
  'Map metadata': 'Donnees cartographiques',
  Provider: 'Fournisseur',
  'Invite link': 'Lien d invitation',
  Uses: 'Utilisations',
  'Create invite': 'Creer une invitation',
  'Budget and exports': 'Budget et exports',
  'Load budget': 'Charger le budget',
  Calendar: 'Calendrier',
  PDF: 'PDF',
  Planned: 'Planifie',
  Paid: 'Paye',
  Remaining: 'Restant',
  'Audit log': 'Journal d audit',
  'Load audit': 'Charger l audit',
  'Make a payment': 'Effectuer un paiement',
  'Payment method': 'Methode de paiement',
  Mobile: 'Mobile',
  Card: 'Carte',
  'Target type': 'Type de cible',
  Total: 'Total',
  'Event ticket': 'Billet evenementiel',
  'Submit payment': 'Soumettre le paiement',
  'Trip feedback': 'Avis sur le voyage',
  Tags: 'Etiquettes',
  'Save feedback': 'Enregistrer l avis',
  Members: 'Membres',
  'Group discussions': 'Discussions du groupe',
  'New topic': 'Nouveau sujet',
  Message: 'Message',
  'Start discussion': 'Demarrer la discussion',
  Reply: 'Repondre',
  'Post reply': 'Publier la reponse',
  'Share media with this group': 'Partager un media avec ce groupe',
  Caption: 'Legende',
  'Media type': 'Type de media',
  Photo: 'Photo',
  Video: 'Video',
  'Media URL': 'URL du media',
  'Upload file': 'Importer un fichier',
  'Share media': 'Partager le media',
  'Account created. You can now login.': 'Compte cree. Vous pouvez maintenant vous connecter.',
  'Login successful.': 'Connexion reussie.',
  'Logged out successfully.': 'Deconnexion reussie.',
  'Itinerary created successfully.': 'Itineraire cree avec succes.',
  'Generated itinerary saved.': 'Itineraire genere enregistre.',
  'Draft itinerary generated.': 'Brouillon d itineraire genere.',
  'Profile preferences updated.': 'Preferences du profil mises a jour.',
  'Payment complete. Receipt generated.': 'Paiement effectue. Recu genere.',
  'Invite link created.': 'Lien d invitation cree.',
  'Trip progress updated.': 'Progression du voyage mise a jour.',
  'Feedback recorded.': 'Avis enregistre.',
  'Please login to create an itinerary.': 'Veuillez vous connecter pour creer un itineraire.',
  'Title and location are required.': 'Le titre et le lieu sont requis.',
};

export const FR_PLACEHOLDERS = {
  'Douala, beach, hotel': 'Douala, plage, hotel',
  'Beach Escape': 'Escapade a Kribi',
  'Seaside Hotel': 'Hotel a Akwa',
  'Surf Lesson': 'Visite culinaire',
  Uluwatu: 'Musee national',
  food: 'cuisine',
  'Cameroon Travelers': 'Voyageurs du Cameroun',
  'Share tips and meet other travellers': 'Partager des conseils et rencontrer d autres voyageurs',
  'Add comment': 'Ajouter un commentaire',
  'Share with username': 'Partager avec un utilisateur',
  'hotel id': 'id hotel',
  bob: 'paul',
  Airport: 'Aeroport',
  'hotel, activity-1': 'hotel, activite-1',
  'Best local guides': 'Meilleurs guides locaux',
  'Share a question or tip': 'Partager une question ou un conseil',
  'Write a reply': 'Ecrire une reponse',
  'Sunset in Kribi': 'Coucher de soleil a Kribi',
  'https://example.com/photo.jpg': 'https://exemple.com/photo.jpg',
  'What worked well?': 'Qu est-ce qui a bien fonctionne ?',
};

/* ---------------------------------------------------------------------
   The redesigned pages.

   Kept in the same dictionary as the original screens so a phrase that
   appears on both is translated once and identically.
   --------------------------------------------------------------------- */
export const FR_NEW = {
  'About': 'À propos',
  'Accommodation': 'Hébergement',
  'Add a place': 'Ajouter un lieu',
  'Add to trip': 'Ajouter au voyage',
  'All': 'Tout',
  'All discussions': 'Toutes les discussions',
  'Any price': 'Tous les prix',
  'Ask questions, share advice and discover Cameroon with other travellers.': "Posez des questions, partagez des conseils et découvrez le Cameroun avec d'autres voyageurs.",
  'Back to Explore': "Retour à l'exploration",
  'Best season': 'Meilleure saison',
  'Build my trip': 'Créer mon voyage',
  'Building…': 'Création…',
  'Cancel': 'Annuler',
  'Chat': 'Discussion',
  'Clear all': 'Tout effacer',
  'Clear filters': 'Effacer les filtres',
  'Continue your trip': 'Reprendre votre voyage',
  'Coordinates': 'Coordonnées',
  'Create your trip': 'Créer votre voyage',
  'Destination': 'Destination',
  'Difficulty': 'Difficulté',
  'Discover incredible places, build your perfect itinerary, and travel Cameroon with confidence.': 'Découvrez des lieux remarquables, composez votre itinéraire idéal et parcourez le Cameroun en confiance.',
  'Discussions': 'Discussions',
  'Duration (hours)': 'Durée (heures)',
  'Experience': 'Expérience',
  'Explore': 'Explorer',
  'Explore Cameroon': 'Explorer le Cameroun',
  'Explore Cameroon,': 'Explorez le Cameroun,',
  'Explore all': 'Tout explorer',
  'Featured places': 'Lieux à la une',
  'Filters': 'Filtres',
  'Free': 'Gratuit',
  'Generate my itinerary': 'Générer mon itinéraire',
  'Get started': 'Commencer',
  'Guide': 'Guide',
  'Hotels': 'Hôtels',
  'Join group': 'Rejoindre le groupe',
  'Join this group to join the conversation.': 'Rejoignez ce groupe pour participer à la conversation.',
  'Joined': 'Membre',
  'Kind of post': 'Type de publication',
  'Leave': 'Quitter',
  'Leave group': 'Quitter le groupe',
  'Map': 'Carte',
  'Message the group…': 'Écrire au groupe…',
  'More detail': 'Plus de détails',
  'More trip tools': 'Plus doutils de voyage',
  'My groups': 'Mes groupes',
  'My trips': 'Mes voyages',
  'Nearby places': 'Lieux à proximité',
  'No trips yet': 'Aucun voyage pour le moment',
  'Number of days': 'Nombre de jours',
  'Open route in Google Maps': "Ouvrir l'itinéraire dans Google Maps",
  'Open trip →': 'Ouvrir le voyage →',
  'Optional': 'Facultatif',
  'Places': 'Lieux',
  'Plan': 'Programme',
  'Plan manually': 'Planifier moi-même',
  'Popular destinations': 'Destinations populaires',
  'Popular groups': 'Groupes populaires',
  'Post': 'Publier',
  'Price': 'Prix',
  'Profile': 'Profil',
  'Question': 'Question',
  'Recent travel photos': 'Photos de voyage récentes',
  'Recommendation': 'Recommandation',
  'Recommended': 'Recommandé',
  'Recommended experiences': 'Expériences recommandées',
  'Restaurants': 'Restaurants',
  'Reviews': 'Avis',
  'Save checkpoint': 'Enregistrer le point',
  'Save this place': 'Enregistrer ce lieu',
  'Saved': 'Enregistré',
  'See more': 'Voir plus',
  'Show more places': 'Afficher plus de lieux',
  'Start a discussion': 'Lancer une discussion',
  'Start exploring': "Commencer l'exploration",
  'Still loading the full catalogue…': 'Chargement du catalogue complet…',
  'This trip is empty': 'Ce voyage est vide',
  'Tourist sites': 'Sites touristiques',
  'Trip cost': 'Coût du voyage',
  'Trips': 'Voyages',
  'Typical cost': 'Coût habituel',
  'Unanswered': 'Sans réponse',
  'What would you like to ask or share?': 'Que souhaitez-vous demander ou partager ?',
  'Your Way': 'À votre façon',
};

export const FR_TEXT = { ...FR_BASE, ...FR_NEW };
